spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/test
    username: test_user
    password: pass
    driverClassName: org.postgresql.Driver
    initialization-mode: never
